workflows:
  ios-release:
    name: iOS Release IPA
    instance_type: mac_mini_m2
    max_build_duration: 120
    working_directory: app_gif
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Build unsigned iOS release IPA for sideloading
        script: |
          flutter build ios --release --no-codesign
          mkdir -p build/ios/ipa/Payload
          cp -R build/ios/iphoneos/Runner.app build/ios/ipa/Payload/Runner.app
          cd build/ios/ipa
          /usr/bin/zip -qry Runner-release-unsigned.ipa Payload
    artifacts:
      - build/ios/ipa/Runner-release-unsigned.ipa
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - leyyoudian@example.com
        notify:
          success: true
          failure: true
